name = "DiscreteFunctions"
uuid = "b8ca354f-f9b0-480f-9b77-7fb0ec324754"
authors = ["Kirill Tsaregorodtsev", "MSU"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
